@startmindmap
* 充电桩项目

** 商户模块
*** 鉴权注解用法NotAuth
**** 手机号注册

** 用户模块
*** 注册的方式
**** 手机号注册
**** 第三方注册
***** 微信
*** 登陆的方式
**** 手机验证码登陆
**** 用户名密码登陆
**** 第三方登陆
***** 微信
*** 用户类型
**** 个人用户
**** 企业用户

** 支付模块
*** 钱包类型
**** 平台钱包
**** 商家-用户线下钱包
**** 商家钱包
*** 支付类型
**** 平台钱包支付
**** 商家-用户线下钱包支付
**** 第三方支付
***** 微信
***** 支付宝

** 订单模块
*** 订单的状态
**** 初始状态
***** 0：创建，用户扫码后立即创建一张订单；如果创建即确认，此状态则作为保留状态
***** 1：订单已确认，用户确认充电，充电枪状态检查，具备充电条件，平台将发送激活充电枪的指令，激活充电枪
**** 中间状态
***** 10：充电中，充电枪已插入车中，正在进行充电；如果不显示此状态，此状态可作为保留状态
***** 11：充电成功，充电已经结束；尚未支付
***** 12：充电失败，充电过程出现问题，未能正常结束
***** 20：已支付
***** 21：支付失败
**** 完结状态
***** 30：订单已作废，订单创建后，用户在进行充电前主动取消，如果创建即确认，此状态则作为保留状态
***** 31：订单已完成，成功的订单完结状态
***** 32：订单失败完成，充电失败、没有成功支付或其他原因而需要完结的订单






@endmindmap