@startuml

sprite $bProcess jar:archimate/business-process
sprite $aService jar:archimate/application-service
sprite $aComponent jar:archimate/application-component
sprite $bEvent jar:archimate/business-event
sprite $aEquipment jar:archimate/physical-equipment



node  "用户客户端" #TECHNOLOGY{
    actor #Business "H5"  as H5
    actor #Business "微信小程序"  as 微信小程序
}

node  "商户客户端" #TECHNOLOGY{
    actor #Business "H5"  as 商户客户端H5
}

node  "管理后台客户端" #TECHNOLOGY{
    actor #Business "H5"  as 管理后台客户端H5
}

archimate #Business "nginx for http"  as http服务nginx

archimate #Business "管理后台服务"  as 管理后台服务

node  "运营平台服务集群" #TECHNOLOGY{
    archimate #Business "用户中心"  as 用户模块
    archimate #Business "商户中心"  as 商户模块
    archimate #Business "订单中心"  as 订单模块
    archimate #Business "支付中心"  as 支付模块
    archimate #Business "充电桩中心"  as 充电桩模块

    archimate #Business "注册中心"  as 注册中心
    archimate #Business "API网关"  as API网关
}

node  "充电桩" #TECHNOLOGY{
    archimate #Business "充电枪"  as 充电枪 <<physical-equipment>>
}

archimate #Business "nginx for tcp"  as 充电桩平台nginx

node  "充电桩平台路由服务" #TECHNOLOGY{
    archimate #Business "zookeeper实现\n用来注册及发现指定充电枪所连接的充电桩平台服务地址"  as 充电桩平台路由服务
}

node  "充电桩平台服务集群" #TECHNOLOGY{
    archimate #Business "充电桩平台服务\n同时支持联行协议(与充电桩保持长连接)和http协议"  as 充电桩平台服务
}


用户客户端 -down-> http服务nginx:http
商户客户端 -down-> http服务nginx:http
管理后台客户端 -down-> http服务nginx:http

http服务nginx -down-> API网关
http服务nginx -down-> 管理后台服务:客户端访问
管理后台服务 -down-> http服务nginx:通过nginx访问微服务

充电桩模块 -down-> 充电桩平台路由服务:发现socket连接所在的充电桩平台节点地址

充电桩模块 -down-> 充电桩平台服务集群:http下发指令
充电桩平台服务集群 -up-> 充电桩平台路由服务:注册地址
充电桩平台服务集群 -down-> 充电桩:下发指令

充电桩平台nginx -up-> 充电桩平台服务集群:转发
充电桩 -up-> 充电桩平台nginx:充电桩主动建立tcp连接，推送数据




@enduml
