@startuml

/'中心表'/
!define CenterTable(name,desc) class name as "desc" << (C,#FF3030) >>  #CORNSILK
/'子集表'/
!define SubsetTable(name,desc) class name as "desc" << (S,#FFDEAD) >>
/'子集-中心表'/
!define SubsetCenterTable(name,desc) class name as "desc" << (S,#FF3030) >>  #CORNSILK
/'功能表'/
!define FunctionTable(name,desc) class name as "desc" << (F,#FFF0F5) >>
/'关系表'/
!define RelationTable(name,desc) class name as "desc" << (R,#D9F4EF) >>  #D9F4EF

/'业务流程-中心表'/
!define BusinessCenterTable(name,desc) class name as "desc" << (B,#FF3030) >> #CORNSILK
/'业务流程表'/
!define BusinessTable(name,desc) class name as "desc" << (B,#AB82FF) >>
/'行为表'/
!define BehaviourRecordTable(name,desc) class name as "desc" << (H,#8DB6CD) >>
/'验证表'/
!define VerificationTable(name,desc) class name as "desc" << (V,#B5B5B5) >>



!define varchar(x) varchar x
!define tinyint(x) tinyint x
!define smallint(x) smallint x
!define mediumint(x) mediumint x
!define int(x) bigint x
!define bigint(x) bigint x
!define decimal(x,y) decimal x,y

hide methods
hide stereotypes

skinparam class {
    BackgroundColor white
    ArrowColor red
    BorderColor MidnightBlue
}



package 充电桩模块 <<Frame>> #EAEAEA{

    CenterTable(charge_station, "充电站表\n(标识一个充电站)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家id',
        `name` varchar(256) DEFAULT '' COMMENT '名称',
        `address` varchar(256) DEFAULT '' COMMENT '地址',
        `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
        `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
        `service_type` tinyint(4) DEFAULT NULL COMMENT '运营类型',
        `service_status` tinyint(4) DEFAULT NULL COMMENT '运营状态',
        `station_type` tinyint(4) DEFAULT NULL COMMENT '站点类型',
        `register_time` int(32) unsigned DEFAULT NULL COMMENT '投运时间',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    CenterTable(charge_pile, "充电桩表\n(标识一个充电桩)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `cs_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电站id',
        `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家id，冗余字段',
        `fee_rule_id` bigint(64) unsigned DEFAULT NULL COMMENT '计费规则id',
        `fee_rule_sn` int(32) unsigned NOT NULL COMMENT '下发到充电桩的计费规则id，冗余字段',
        `name` varchar(256) DEFAULT '' COMMENT '名称',
        `service_object` tinyint(4) DEFAULT NULL COMMENT '服务对象',
        `service_status` tinyint(4) DEFAULT NULL COMMENT '运营状态',
        `register_time` int(32) unsigned DEFAULT NULL COMMENT '登记时间，统一使用时间戳格式，精确到秒',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    CenterTable(charge_gun, "充电枪表\n(标识一个充电枪)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `cp_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电桩id',
        `sn` tinyint(4) unsigned DEFAULT NULL COMMENT '枪口编号 1-255',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(cg_quantity_record, "电表，充电桩发送表底检测数据记录表\n(标识一次数据检测事件)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `cg_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电枪id',
        `cp_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电桩id，冗余字段',
        `sn` tinyint(4) unsigned DEFAULT NULL COMMENT '枪口编号 1-255',
        `quantity` smallint(6) unsigned DEFAULT NULL COMMENT '电表底值/电量-总，比例 0.01',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(cg_event_record, "充电桩事件发送记录表\n(标识一次事件)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `cg_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电枪id',
        `event_type` tinyint(4) DEFAULT '-1' COMMENT '事件类型',
        `event_id` bigint(64) unsigned DEFAULT NULL COMMENT '事件序列id',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(cg_server_event_record, "平台回复事件记录表\n(标识一次平台指令事件)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `cg_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电枪id',
        `event_type` tinyint(4) DEFAULT '-1' COMMENT '事件类型',
        `event_id` bigint(64) unsigned DEFAULT NULL COMMENT '事件序列id',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(cg_status, "充电枪状态记录表\n(标识一次充电枪状态上报行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `cg_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电枪id',
        `sn` bigint(32) unsigned DEFAULT NULL COMMENT '订单编号',
        `work_status` tinyint(4) DEFAULT NULL COMMENT '工作状态',
        `connect_status` tinyint(4) DEFAULT NULL COMMENT '连接状态',
        `output_contactor_status` tinyint(4) DEFAULT NULL COMMENT '输出接触器状态',
        `electronic_lock_status` tinyint(4) DEFAULT NULL COMMENT '电子锁状态',
        `fault_number` tinyint(4) DEFAULT NULL COMMENT '故障码',
        `voltage` smallint(6) unsigned DEFAULT NULL COMMENT '充电电压',
        `current` smallint(6) unsigned DEFAULT NULL COMMENT '充电电流',
        `bms_voltage` smallint(6) unsigned DEFAULT NULL COMMENT 'bms需求电压',
        `bms_current` smallint(6) unsigned DEFAULT NULL COMMENT 'bms需求电流',
        `bms_model` tinyint(4) DEFAULT NULL COMMENT 'bms充电模式',
        `input_quantity` smallint(6) unsigned DEFAULT NULL COMMENT '已充电量',
        `power` smallint(6) unsigned DEFAULT NULL COMMENT '充电功率',
        `a_voltage` smallint(6) unsigned DEFAULT NULL COMMENT '交流输出A相电压',
        `a_current` smallint(6) unsigned DEFAULT NULL COMMENT '交流输出A相电流',
        `b_voltage` smallint(6) unsigned DEFAULT NULL COMMENT '交流输出B相电压',
        `b_current` smallint(6) unsigned DEFAULT NULL COMMENT '交流输出B相电流',
        `c_voltage` smallint(6) unsigned DEFAULT NULL COMMENT '交流输出C相电压',
        `c_current` smallint(6) unsigned DEFAULT NULL COMMENT '交流输出C相电流',
        `input_duration` int(8) DEFAULT NULL COMMENT '已充时长，分钟',
        `left_duration` int(8) DEFAULT NULL COMMENT '剩余充电时间预估，分钟',
        `cp_temperature` tinyint(4) DEFAULT NULL COMMENT '充电桩内部温度',
        `cg_temperature` tinyint(4) DEFAULT NULL COMMENT '枪头温度',
        `input_start_quantity` smallint(6) unsigned DEFAULT NULL COMMENT '充电开始时电表读数',
        `input_now_quantity` smallint(6) unsigned DEFAULT NULL COMMENT '当前电表读数',
        `now_soc` tinyint(4) DEFAULT NULL COMMENT '当前 SOC',
        `cell_highest_temperature` tinyint(4) DEFAULT NULL COMMENT '单体电池最高温度',
        `cell_highest_voltage` smallint(6) unsigned DEFAULT NULL COMMENT '单体电池最高电压',
        `fee_id` bigint(64) unsigned DEFAULT NULL COMMENT '计费模型 id',
        `spike_quantity` smallint(6) unsigned DEFAULT NULL COMMENT '尖电量',
        `spike_quantity_fee` smallint(6) unsigned DEFAULT NULL COMMENT '尖电费',
        `spike_server_fee` smallint(6) unsigned DEFAULT NULL COMMENT '尖服务费',
        `peak_quantity` smallint(6) unsigned DEFAULT NULL COMMENT '峰电量',
        `peak_quantity_fee` smallint(6) unsigned DEFAULT NULL COMMENT '峰电费',
        `peak_server_fee` smallint(6) unsigned DEFAULT NULL COMMENT '峰服务费',
        `flat_quantity` smallint(6) unsigned DEFAULT NULL COMMENT '平电量',
        `flat_quantity_fee` smallint(6) unsigned DEFAULT NULL COMMENT '平电费',
        `flat_server_fee` smallint(6) unsigned DEFAULT NULL COMMENT '平服务费',
        `valley_quantity` smallint(6) unsigned DEFAULT NULL COMMENT '谷电量',
        `valley_quantity_fee` smallint(6) unsigned DEFAULT NULL COMMENT '谷电费',
        `valley_server_fee` smallint(6) unsigned DEFAULT NULL COMMENT '谷服务费',
        `now_quantity_fee` smallint(6) unsigned DEFAULT NULL COMMENT '当前充电电费',
        `now_total_fee` smallint(6) unsigned DEFAULT NULL COMMENT '当前充电总费用',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }
}



package 商户模块 <<Frame>> #EAEAEA{
    CenterTable(merchant, "商家表\n(标识一个商家)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `id_number` varchar(256) DEFAULT '' COMMENT '营业执照',
        `name` varchar(256) DEFAULT '' COMMENT '名称',
        `address` varchar(256) DEFAULT '' COMMENT '地址',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    CenterTable(merchant_admin, "商家管理员表\n(标识一个商家管理员)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家id，属于哪个商家的管理员',
        `phone` varchar(256) DEFAULT '' COMMENT '手机',
        `user_name` varchar(256) DEFAULT '' COMMENT '用户名，可用作登陆',
        `real_name` varchar(256) DEFAULT '' COMMENT '真实姓名',
        `password` varchar(256) DEFAULT '' COMMENT '密码',
        `token` varchar(256) DEFAULT '' COMMENT '鉴权token',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    FunctionTable(merchant_profit_shard, "商家收益分配配置表\n(标识一个商家管理员)"){
        `merchant_admin_id` bigint(64) unsigned NOT NULL COMMENT '管理员id,主键',
        `rate` decimal(10,2) DEFAULT NULL COMMENT '分成比例',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`merchant_admin_id`)
    }

    FunctionTable(merchant_role, "商家角色表\n(标识一个商家角色,有如下几类1.超级管理员，拥有所有权限，包括创建角色与添加管理员的权限；\n2.股东管理员，可查看分成情况；\n3.普通管理员，仅查看权限。\n4.自定义角色)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `merchant_id` bigint(64) unsigned DEFAULT '0' COMMENT '商家id，哪个商家创建的；默认为0，即系统创建',
        `name` varchar(256) DEFAULT '' COMMENT '角色名称；',
        `description` varchar(256) DEFAULT '' COMMENT '描述',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    FunctionTable(merchant_resource, "资源表\n(标识一个资源"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `uri` varchar(256) NOT NULL COMMENT '资源uri',
        `name` varchar(256) DEFAULT '' COMMENT '资源名称；',
        `description` varchar(256) DEFAULT '' COMMENT '描述',
        `parent_id` bigint(64) unsigned DEFAULT NULL COMMENT '上级id (顶级为0)',
        `code` varchar(128) DEFAULT '' COMMENT '资源编码',
        `type` tinyint(4) NOT NULL COMMENT '资源类型 1：菜单，2：方法（改为是否菜单标记1是，其它值为否）',
        `is_leaf` bit(1) NOT NULL COMMENT '是否叶子 0：否，1：是',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    RelationTable(merchant_admin_role, "商家管理员-角色关系表\n(标识一个商家管理员-角色)"){
        `merchant_admin_id` bigint(64) unsigned NOT NULL COMMENT '管理员id,第一主键',
        `merchant_role_id` varchar(256) DEFAULT '' COMMENT '角色id。第二主键',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`merchant_admin_id`,`merchant_role_id`)
    }

    RelationTable(merchant_role_resource, "商家角色资源权限关系表\n(标识一个商家角色资源权限)"){
        `merchant_role_id` varchar(256) DEFAULT '' COMMENT '角色id。第一主键',
        `merchant_resource_id` varchar(256) DEFAULT '' COMMENT '角色id。第二主键',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`merchant_role_id`,`merchant_resource_id`)
    }

    BehaviourRecordTable(merchant_operate_record, "商家管理员操作记录表\n(标识一次商家管理员操作行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `merchant_admin_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家管理员id',
        `url` varchar(256) DEFAULT '' COMMENT '操作接口',
        `param` varchar(1024) DEFAULT '' COMMENT '接口参数',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(merchant_login_record, "商家管理员登陆记录表\n(标识一次商家管理员登陆行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `merchant_admin_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家管理员id',
        `phone_models` varchar(256) DEFAULT '' COMMENT '手机型号',
        `device_id` varchar(256) DEFAULT '' COMMENT '设备ID',
        `imei` varchar(256) DEFAULT NULL COMMENT '设备标识',
        `ip` varchar(256) DEFAULT NULL COMMENT 'ip地址',
        `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
        `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    FunctionTable(merchant_third, "第三方登录商家管理员表\n(标识一个第三方账户，关联商家管理员)"){
        `type` tinyint(4) NOT NULL COMMENT '类型，1：支付宝；2：微信',
        `third_id` varchar(256) NOT NULL COMMENT '第三方账户标识',
        `merchant_admin_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家管理员id',
        `name` varchar(256) DEFAULT '' COMMENT '名称',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`type`,`third_id`)
    }

    RelationTable(merchant_user, "商家-用户表\n(标识一个商家下面的用户)"){
        `merchant_id` bigint(64) unsigned NOT NULL COMMENT '商家id，第一主键',
        `user_id` bigint(64) unsigned NOT NULL COMMENT '商家id，第二主键',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`merchant_id`,`user_id`)
    }

    FunctionTable(fee_rule, "计费规则表\n(标识一个计费规则)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `sn` int(32) unsigned NOT NULL COMMENT '下发到充电桩的id',
        `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家id',
        `name` varchar(256) DEFAULT '' COMMENT '名称',
        `description` varchar(256) DEFAULT '' COMMENT '明细描述',
        `status` tinyint(4) DEFAULT '-1' COMMENT '状态',
        `rule_version` int(8) DEFAULT '-1' COMMENT '规则的版本',

        `expire_time` int(32) unsigned DEFAULT NULL COMMENT '失效时间',
        `spike_price` int(32) unsigned DEFAULT NULL COMMENT '尖电价',
        `peak_price` int(32) unsigned DEFAULT NULL COMMENT '峰电价',
        `flat_price` int(32) unsigned DEFAULT NULL COMMENT '平电价',
        `valley_price` int(32) unsigned DEFAULT NULL COMMENT '谷电价',
        `spike_server_price` int(32) unsigned DEFAULT NULL COMMENT '尖时段服务费电价',
        `peak_server_price` int(32) unsigned DEFAULT NULL COMMENT '峰时段服务费电价',
        `flat_server_price` int(32) unsigned DEFAULT NULL COMMENT '平时段服务费电价',
        `valley_server_price` int(32) unsigned DEFAULT NULL COMMENT '谷时段服务费电价',

        `t0000_0030` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0030_0100` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0100_0130` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0130_0200` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0200_0230` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0230_0300` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0300_0330` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0330_0400` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0400_0430` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0430_0500` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0500_0530` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0530_0600` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0600_0630` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0630_0700` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0700_0730` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0730_0800` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0800_0830` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0830_0900` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0900_0930` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t0930_1000` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',

        `t1000_1030` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1030_1100` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1100_1130` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1130_1200` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1200_1230` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1230_1300` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1300_1330` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1330_1400` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1400_1430` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1430_1500` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1500_1530` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1530_1600` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1600_1630` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1630_1700` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1700_1730` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1730_1800` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1800_1830` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1830_1900` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1900_1930` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t1930_2000` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',

        `t2000_2030` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t2030_2100` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t2100_2130` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t2130_2200` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t2200_2230` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t2230_2300` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t2300_2330` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',
        `t2330_0000` tinyint(4) DEFAULT '-1' COMMENT '费率号（0：尖，1：峰，2：平，3： 谷）',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }


}

package 用户模块 <<Frame>> #EAEAEA{
    CenterTable(user, "用户表\n(标识一个用户)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `type` tinyint(4) DEFAULT '-1' COMMENT '用户类型,0:个人用户；1：企业用户；-1：未知',
        `phone` varchar(256) DEFAULT '' COMMENT '手机，加唯一索引，可用作登陆',
        `user_name` varchar(256) DEFAULT '' COMMENT '用户名，加唯一索引，可用作登陆',
        `password` varchar(256) DEFAULT '' COMMENT '密码',
        `status` tinyint(4) DEFAULT NULL COMMENT '状态',
        `token` varchar(256) DEFAULT '' COMMENT '鉴权token',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    SubsetTable(user_detail, "用户详情表\n(标识一个用户)"){
        `user_id` bigint(64) unsigned NOT NULL COMMENT '主键，等同于user表的id',
        `group_id` bigint(64) unsigned DEFAULT NULL COMMENT '团体所属，如个人用户属于某个企业用户，自关联于user_id',
        `real_name` varchar(256) DEFAULT '' COMMENT '真实姓名、企业名称',
        `nick_name` varchar(256) DEFAULT '' COMMENT '昵称',
        `id_number` varchar(256) DEFAULT '' COMMENT '对于个人用户，身份证号；对于企业用户，营业执照',
        `sex` tinyint(4) DEFAULT NULL COMMENT '性别,0:女；1：男；-1：未知',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`user_id`)
    }

    FunctionTable(user_third, "第三方登录用户表\n(标识一个第三方账户，关联用户)"){
        `type` tinyint(4) NOT NULL COMMENT '类型，1：支付宝；2：微信',
        `third_id` varchar(256) NOT NULL COMMENT '第三方账户标识',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
        `name` varchar(256) DEFAULT NULL COMMENT '第三方账户姓名',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`type`,`third_id`)
    }

    BehaviourRecordTable(user_login_record, "用户登陆记录表\n(标识一次用户登陆行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
        `phone_models` varchar(256) DEFAULT '' COMMENT '手机型号',
        `device_id` varchar(256) DEFAULT '' COMMENT '设备ID',
        `imei` varchar(256) DEFAULT NULL COMMENT '设备标识',
        `ip` varchar(256) DEFAULT NULL COMMENT 'ip地址',
        `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
        `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    CenterTable(car, "车辆表\n(标识一个车辆)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
        `vin` varchar(256) DEFAULT '' COMMENT 'vin码',
        `license_number` varchar(256) DEFAULT '' COMMENT '车辆号码',
        `self_number` varchar(256) DEFAULT '' COMMENT '自编号',
        `brand` varchar(256) DEFAULT '' COMMENT '品牌',
        `category` varchar(256) DEFAULT '-1' COMMENT '车辆分类',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }
}

package 订单模块 <<Frame>> #EAEAEA{
    BusinessCenterTable(order, "订单表\n(标识一个订单)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `status` tinyint(4) DEFAULT '-1' COMMENT ' 0：创建，用户扫码后立即创建一张订单；如果创建即确认，此状态则作为保留状态；
1：订单已确认，用户确认充电，充电枪状态检查，具备充电条件，平台将发送激活充电枪的指令，激活充电枪；
10：充电中，充电枪已插入车中，正在进行充电；如果不显示此状态，此状态可作为保留状态；
11：充电成功，充电已经结束；尚未支付；
12：充电失败，充电过程出现问题，未能正常结束；
20：已支付；
21：支付失败；
30：订单已作废，订单创建后，用户在进行充电前主动取消，如果创建即确认，此状态则作为保留状态；
31：订单已完成，成功的订单完结状态。
32：订单失败完成，充电失败、没有成功支付或其他原因而需要完结的订单； ',

        `sn` bigint(32) unsigned DEFAULT NULL COMMENT '订单编号',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
        `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商户id',
        `cg_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电枪id',
        `money` decimal(10,2) DEFAULT NULL COMMENT '金额',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
         PRIMARY KEY (`id`)
    }

    SubsetTable(order_detail, "订单详情表\n(标识一个订单)"){
         `order_id` bigint(64) unsigned NOT NULL COMMENT '主键',
         `cp_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电桩id',
         `car_id` bigint(64) unsigned DEFAULT NULL COMMENT '车辆id',

         `version` int(8) DEFAULT '0' COMMENT '版本',
         `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
         `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
         `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
         `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
         PRIMARY KEY (`order_id`)
    }
}


package 支付模块 <<Frame>> #EAEAEA{

    SubsetCenterTable(user_wallet, "用户钱包表\n(标识一个用户钱包)"){
        `user_id` bigint(64) unsigned NOT NULL COMMENT '主键，用户id',
        `money` decimal(10,2) DEFAULT NULL COMMENT '账户余额',
        `status` tinyint(4) DEFAULT NULL COMMENT '状态',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`user_id`)
    }

    SubsetCenterTable(merchant_wallet, "商户钱包表\n(标识一个商户钱包，用来记录商户的账户余额)"){
      `merchant_id` bigint(64) unsigned NOT NULL COMMENT '主键，商户id',
      `money` decimal(10,2) DEFAULT NULL COMMENT '账户余额',
      `status` tinyint(4) DEFAULT NULL COMMENT '状态',

      `version` int(8) DEFAULT '0' COMMENT '版本',
      `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
      `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
      `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      PRIMARY KEY (`merchant_id`)
    }

    SubsetCenterTable(merchant_user_wallet, "商户-用户线下钱包表\n(标识一个商户-用户线下钱包，记录账户余额)"){
      `merchant_id` bigint(64) unsigned NOT NULL COMMENT '第一主键，商户id',
      `user_id` bigint(64) unsigned NOT NULL COMMENT '第二主键，用户户id',
      `money` decimal(10,2) DEFAULT NULL COMMENT '账户余额',
      `status` tinyint(4) DEFAULT NULL COMMENT '状态',

      `version` int(8) DEFAULT '0' COMMENT '版本',
      `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
      `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
      `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      PRIMARY KEY (`merchant_id`,`user_id`)
    }

    BehaviourRecordTable(mu_wallet_deposit_record, "商户-用户线下钱包充值记录表\n(标识一次充值行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商户id',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
        `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
        `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：充值失败；1：充值成功',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者，需要赋值商家管理员id',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(mu_pay_record, "商户-用户线下钱包支付记录表\n(标识一次通过余额支付的行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商户id',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
        `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
        `sn` varchar(256) DEFAULT '' COMMENT '流水号',
        `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：支付失败；1：支付成功',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }


    BehaviourRecordTable(user_pay_record, "支付记录表\n(标识一次支付行为)"){
         `id` bigint(64) unsigned NOT NULL COMMENT '主键',
         `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
         `order_id` bigint(64) unsigned DEFAULT NULL COMMENT '订单id',
         `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
         `type` tinyint(4) DEFAULT '-1' COMMENT '支付类型；0：微信；1：支付宝；2：账户余额支付；3线下钱包支付',
         `sn_third` varchar(256) DEFAULT '' COMMENT '第三方流水标识；如果是余额支付；则为user_wallet_pay_record表的sn字段；如果是线下钱包支付，则为mu_pay_则为mu_user_pay_record表的sn字段',
         `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：支付失败；1：支付成功',

         `version` int(8) DEFAULT '0' COMMENT '版本',
         `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
         `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
         `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
         `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
         PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(user_deposit_record, "充值记录表\n(标识一次充值行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id,钱包id',
        `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
        `type` tinyint(4) DEFAULT '-1' COMMENT '支付类型；0：微信；1：支付宝',
        `sn` varchar(256) DEFAULT '' COMMENT '第三方流水标识',
        `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：充值失败；1：充值成功',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

    BehaviourRecordTable(user_wallet_pay_record, "用户钱包支付记录表\n(标识一次通过用户钱包支付的行为)"){
        `id` bigint(64) unsigned NOT NULL COMMENT '主键',
        `sn` varchar(256) DEFAULT '' COMMENT '流水号',
        `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id,钱包id',
        `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
        `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：支付失败；1：支付成功',

        `version` int(8) DEFAULT '0' COMMENT '版本',
        `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
        `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
        PRIMARY KEY (`id`)
    }

  BehaviourRecordTable(merchant_wallet_withdraw_record, "商家钱包提现记录表\n(标识一次商家提现行为)"){
      `id` bigint(64) unsigned NOT NULL COMMENT '主键',
      `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商户id,钱包id',
      `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
      `type` tinyint(4) DEFAULT '-1' COMMENT '支付类型；0：微信；1：支付宝',
      `sn_third` varchar(256) DEFAULT '' COMMENT '第三方流水标识',
      `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：提现失败；1：提现成功',

      `version` int(8) DEFAULT '0' COMMENT '版本',
      `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
      `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
      `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      PRIMARY KEY (`id`)
  }


}



/'用户模块'/
user -- user_detail : 1:1
user_third }-- user : 1:n
user_login_record }-- user : 1:n
/'车辆'/
car }-- user : 1:n



/'商家模块'/
merchant_admin }-- merchant : 1:n
merchant_admin --{ merchant_admin_role : 1:n
merchant_role --{ merchant_admin_role : 1:n
merchant_role --{ merchant_role_resource : 1:n
merchant_role --{ merchant : 1:n

merchant_resource --{ merchant_role_resource : 1:n

merchant_operate_record }-- merchant_admin : 1:n
merchant_login_record }-- merchant_admin : 1:n
merchant_third }-- merchant_admin : 1:n

merchant_profit_shard -- merchant_admin : 1:1

merchant_user }-- merchant : 1:n
merchant_user }-- user : 1:n



/'计费规则'/
fee_rule }-- merchant : 1:n



/'订单模块'/
order -- order_detail : 1:1
order }-- user : 1:n
order }-- charge_gun : 1:n
order_detail }-- car : 1:n
order }.. merchant : 1:n /'充电桩商家有可能变动，所以，订单记录下单时的商家'/
order_detail }.. charge_pile : 1:n



/'支付模块'/
/'商户钱包'/
merchant_wallet -- merchant : 1:1
/'提现'/
merchant_wallet_withdraw_record }-- merchant_wallet : 1:n
merchant_wallet_withdraw_record }.. merchant : 1:n


/'用户钱包'/
user_wallet -- user : 1:1
/'支付'/
user_pay_record }-- order : 1:n
user_pay_record }.. user : 1:n
/'余额支付'/
user_wallet_pay_record }-- user_wallet : 1:n
user_wallet_pay_record }.. user : 1:n
user_pay_record }-- user_wallet_pay_record : 1:1
user_pay_record }-- mu_pay_record : 1:1

/'充值'/
user_deposit_record }-- user_wallet : 1:n
user_deposit_record }.. user : 1:n

/'线下钱包'/
merchant_user_wallet -- user : 1:n
merchant_user_wallet -- merchant : 1:n
/'充值'/
mu_wallet_deposit_record }-- merchant_user_wallet : 1:n
/'支付'/
mu_pay_record }-- order : 1:n
mu_pay_record }-- merchant_user_wallet : 1:n


/'充电站模块'/
charge_station }-- merchant : 1:n
/'充电桩'/
charge_pile }-- charge_station : 1:n
charge_pile }.. merchant : 1:n
charge_pile }-- fee_rule : 1:n
/'充电枪'/
charge_gun }-- charge_pile : 1:n
cg_status }-- charge_gun : 1:n
cg_event_record }-- charge_gun : 1:n
cg_server_event_record }-- charge_gun : 1:n
cg_quantity_record }-- charge_gun : 1:n
cg_quantity_record }.. charge_pile : 1:n



/'

用户注册改动的表
user
user_detail
如果是第三方注册：
    user_third

用户登陆改动的表
user
user_login_record

用户扫码充电改动的表
order
order_detail


用户支付改动的表
order
pay_record
如果是余额支付：
    balance_pay_record
    user_wallet

用户支充值改动的表
user_deposit_record
user_wallet

用户创建订单改动的表
order

订单状态：
0：创建，如果创建即确认，此状态则作为保留状态；
10：订单已确认，平台将会激活充电枪；
11：订单已作废，订单创建后，用户在进行充电前主动取消，如果创建即确认，此状态则作为保留状态；
12：订单已完成，成功的订单完结状态。
13：订单失败完成，充电失败、没有成功支付或其他原因而需要完结的订单；
20：充电中，如果不显示此状态，此状态可作为保留状态；
21：充电成功，充电已完成，尚未支付；
22：充电失败；
30：已支付；
31：支付失败；




'/





@enduml


