@startuml

/'中心表'/
!define CenterTable(name,desc) class name as "desc" << (C,#FF4500) >>
/'详情表'/
!define DetailTable(name,desc) class name as "desc" << (D,#FFE4E1) >>

/'卫星表'/
!define SatelliteTable(name,desc) class name as "desc" << (S,#FFDEAD) >>

/'关系表'/
!define RelationTable(name,desc) class name as "desc" << (R,#87CEFA) >>

/'行为表'/
!define BehaviourTable(name,desc) class name as "desc" << (B,#7FFFD4) >>

!define varchar(x) varchar x
!define tinyint(x) tinyint x
!define int(x) bigint x
!define bigint(x) bigint x
!define decimal(x,y) decimal x,y


hide methods
hide stereotypes

CenterTable(car, "车辆表\n(标识一个车辆)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `vin` varchar(256) DEFAULT '' COMMENT 'vin码',
    `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

CenterTable(charge_gun, "充电枪表\n(标识一个充电枪)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `cp_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电桩id',
    `sn` varchar(256) DEFAULT '' COMMENT '枪口编号',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

BehaviourTable(charge_gun_status, "充电枪状态记录表\n(标识一次充电枪状态检查行为)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `cu_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电枪id',
    `capacity` decimal(10,2) DEFAULT NULL COMMENT '容量',
    `voltage` decimal(10,2) DEFAULT NULL COMMENT '电压',
    `current` decimal(10,2) DEFAULT NULL COMMENT '电流',
    `cell_voltage` decimal(10,2) DEFAULT NULL COMMENT '单体电池电压',
    `soc` decimal(10,2) DEFAULT NULL COMMENT '电池 SOC',
    `temperature` decimal(10,2) DEFAULT NULL COMMENT '温度',
    `quantity` decimal(10,2) DEFAULT NULL COMMENT '电量',
    `power` decimal(10,2) DEFAULT NULL COMMENT '功率',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

CenterTable(charge_pile, "充电桩表\n(标识一个充电桩)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `cs_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电站id',
    `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家id',
    `name` varchar(256) DEFAULT '' COMMENT '名称',
    `service_object` tinyint(4) DEFAULT NULL COMMENT '服务对象',
    `service_status` tinyint(4) DEFAULT NULL COMMENT '运营状态',
    `register_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',


    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

BehaviourTable(charge_pile_status, "充电桩状态记录表\n(标识一次充电桩状态检查行为)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `cp_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电桩id',
    `capacity` decimal(10,2) DEFAULT NULL COMMENT '容量',
    `voltage` decimal(10,2) DEFAULT NULL COMMENT '电压',
    `current` decimal(10,2) DEFAULT NULL COMMENT '电流',
    `cell_voltage` decimal(10,2) DEFAULT NULL COMMENT '单体电池电压',
    `soc` decimal(10,2) DEFAULT NULL COMMENT '电池 SOC',
    `temperature` decimal(10,2) DEFAULT NULL COMMENT '温度',
    `quantity` decimal(10,2) DEFAULT NULL COMMENT '电量',
    `power` decimal(10,2) DEFAULT NULL COMMENT '功率',


    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

CenterTable(charge_station, "充电站表\n(标识一个充电站)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商家id',
    `name` varchar(256) DEFAULT '' COMMENT '名称',
    `address` varchar(256) DEFAULT '' COMMENT '地址',
    `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
    `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}


CenterTable(merchant, "商家表\n(标识一个商家)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `phone` varchar(256) DEFAULT '' COMMENT '手机',
    `password` varchar(256) DEFAULT '' COMMENT '密码',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

DetailTable(merchant_detail, "商家详情表\n(标识一个商家)"){
    `merchant_id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `name` varchar(256) DEFAULT '' COMMENT '名称',
    `address` varchar(256) DEFAULT '' COMMENT '地址',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`merchant_id`)
}

BehaviourTable(merchant_login_record, "商家登陆记录表\n(标识一次商家登陆行为)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
    `phone_models` varchar(256) DEFAULT '' COMMENT '手机型号',
    `device_id` varchar(256) DEFAULT '' COMMENT '设备ID',
    `imei` varchar(256) DEFAULT NULL COMMENT '设备标识',
    `ip` varchar(256) DEFAULT NULL COMMENT 'ip地址',
    `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
    `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

SatelliteTable(merchant_third, "第三方登录商户表\n(标识一个第三方账户，关联商户)"){
    `type` tinyint(4) NOT NULL COMMENT '类型，1：支付宝；2：微信',
    `third_id` varchar(256) NOT NULL COMMENT '第三方账户标识',
    `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
    `name` tinyint(4) DEFAULT NULL COMMENT '第三方账户姓名',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`type`,`third_id`)
}

CenterTable(user, "用户表\n(标识一个用户)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `type` tinyint(4) DEFAULT '-1' COMMENT '用户类型,0:个人用户；1：企业用户；-1：未知',
    `phone` varchar(256) DEFAULT '' COMMENT '手机',
    `password` varchar(256) DEFAULT '' COMMENT '密码',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

DetailTable(user_detail, "用户详情表\n(标识一个用户)"){
    `user_id` bigint(64) unsigned NOT NULL COMMENT '主键，等同于user表的id',
    `name` varchar(256) DEFAULT '' COMMENT '姓名、企业名',
    `sex` tinyint(4) DEFAULT '-1' COMMENT '性别,0:女；1：男；-1：未知',
    `money` decimal(10,2) DEFAULT NULL COMMENT '账户余额',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`user_id`)
}

SatelliteTable(user_third, "第三方登录用户表\n(标识一个第三方账户，关联用户)"){
    `type` tinyint(4) NOT NULL COMMENT '类型，1：支付宝；2：微信',
    `third_id` varchar(256) NOT NULL COMMENT '第三方账户标识',
    `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
    `name` tinyint(4) DEFAULT NULL COMMENT '第三方账户姓名',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`type`,`third_id`)
}

BehaviourTable(user_login_record, "用户登陆记录表\n(标识一次用户登陆行为)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
    `phone_models` varchar(256) DEFAULT '' COMMENT '手机型号',
    `device_id` varchar(256) DEFAULT '' COMMENT '设备ID',
    `imei` varchar(256) DEFAULT NULL COMMENT '设备标识',
    `ip` varchar(256) DEFAULT NULL COMMENT 'ip地址',
    `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
    `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

CenterTable(order, "订单表\n(标识一个订单)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `status` tinyint(4) DEFAULT '-1' COMMENT '状态，-1：创建，未确认；0：已确认；1：已支付；2：已完成；-2：已取消',
    `sn` varchar(256) DEFAULT '' COMMENT '订单编号',
    `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
    `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '商户id',
    `cu_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电枪id',
    `money` decimal(10,2) DEFAULT NULL COMMENT '金额',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY (`id`)
}

DetailTable(order_detail, "订单详情表\n(标识一个订单)"){
     `order_id` bigint(64) unsigned NOT NULL COMMENT '主键',
     `cp_id` bigint(64) unsigned DEFAULT NULL COMMENT '充电桩id',

     `version` int(8) DEFAULT '0' COMMENT '版本',
     `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
     `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
     `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     PRIMARY KEY (`order_id`)
}

BehaviourTable(pay_record, "支付记录表\n(标识一次支付行为)"){
     `id` bigint(64) unsigned NOT NULL COMMENT '主键',
     `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
     `order_id` bigint(64) unsigned DEFAULT NULL COMMENT '订单id',
     `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
     `type` tinyint(4) DEFAULT '-1' COMMENT '支付类型；0：微信；1：支付宝',
     `sn_third` varchar(256) DEFAULT '' COMMENT '第三方流水标识',
     `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：支付失败；1：支付成功',

     `version` int(8) DEFAULT '0' COMMENT '版本',
     `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
     `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
     `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     PRIMARY KEY (`id`)
}

BehaviourTable(deposit_record, "充值记录表\n(标识一次充值行为)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `user_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
    `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
    `type` tinyint(4) DEFAULT '-1' COMMENT '支付类型；0：微信；1：支付宝',
    `sn_third` varchar(256) DEFAULT '' COMMENT '第三方流水标识',
    `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：充值失败；1：充值成功',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}

BehaviourTable(withdraw_record, "提现记录表\n(标识一次商家提现行为)"){
    `id` bigint(64) unsigned NOT NULL COMMENT '主键',
    `merchant_id` bigint(64) unsigned DEFAULT NULL COMMENT '用户id',
    `money` decimal(10,2) DEFAULT NULL COMMENT '金额',
    `type` tinyint(4) DEFAULT '-1' COMMENT '支付类型；0：微信；1：支付宝',
    `sn_third` varchar(256) DEFAULT '' COMMENT '第三方流水标识',
    `status` tinyint(4) DEFAULT '-1' COMMENT '状态；0：提现失败；1：提现成功',

    `version` int(8) DEFAULT '0' COMMENT '版本',
    `creator` bigint(64) unsigned DEFAULT NULL COMMENT '创建者',
    `updator` bigint(64) unsigned DEFAULT NULL COMMENT '更新者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
}


/'用户'/
user -- user_detail : 1:1
user_third }-- user : 1:n
user_login_record }-- user : 1:n

/'商家'/
merchant -- merchant_detail : 1:1
merchant_third }-- merchant : 1:n
merchant_login_record }-- merchant : 1:n

/'订单'/
order -- order_detail : 1:1
order }-- user : 1:n
order }-- merchant : 1:n /'充电桩商家有可能变动，所以，订单记录下单时的商家'/
order }-- charge_gun : 1:n
order_detail }-- charge_pile : 1:n


/'支付'/
pay_record }-- order : 1:n
pay_record }-- user : 1:n

/'充值'/
deposit_record }-- user : 1:n

/'提现'/
withdraw_record }-- merchant : 1:n

/'充电站'/
charge_station }-- merchant : 1:n

/'充电桩'/
charge_pile }-- charge_station : 1:n
charge_pile }-- merchant : 1:n
charge_pile_status }-- charge_pile : 1:n


/'充电枪'/
charge_gun }-- charge_pile : 1:n
charge_gun_status }-- charge_gun : 1:n

/'车辆'/
car }-- user : 1:n




@enduml