@startuml
actor 用户
collections 认证中心
database 用户库

用户 -> 认证中心: 登录操作
认证中心 -> 用户库: 校验登录信息是否有效
认证中心 -> 缓存: 有效的登录，存放(key=生成的token+user agent的哈希.防止泄露攻击，如过长可只截取前面一部分),value=用户信息，如id，姓名)
用户 <-- 认证中心 : 认证成功返回session
用户 -> 认证中心: 下次访问头部携带token认证
认证中心 -> 缓存: key=token+user agent的哈希获取用户信息，把用户信息放入请求头中
其他服务 <- 认证中心: 存在且校验成功则跳转到用户请求的其他服务
其他服务 -> 用户: 响应请求
@enduml