@startuml



partition 修改密码 {
    :传入修改的对象（用户名，老密码，新密码）;
    :通过用户名查询要修改密码的用户;
    :校验修改的用户和登陆的用户是否是一个人;
    :获取该用户的密码和老密码进行匹配;
    :新密码加盐;
    :将新密码，更新人set进该用户，更新;
}



partition 忘记密码，修改密码 {
    :传入修改的对象（用户名，手机号，验证码，新密码）;
    :进行验证码校验;
    :校验修改的用户和登陆的用户是否是一个人;
    :通过用户名查询修改密码的用户;
    :新密码加盐;
    :将新密码，更新人set进该用户，更新;

}



partition 修改基本信息 {

}



partition 第一次创建密码 {
    :传入修改的对象（用户名，新密码）;
    :通过用户名查询该用户;
    :校验修改的用户和登陆的用户是否是一个人;
    :判断之前是否有密码;
    :新密码加盐;
    :将新密码，更新人set进该用户，更新;
}



partition 站内信 {
    :新增一条站内信;
    :商家查看自己账号下的所有站内信(已读，未读）;
    :商家点击信件名称查看未读信件，信件自动变成已读;
    :删除已读的站内信;
}


@enduml