@startuml

actor h5
participant 充电桩
participant 充电桩网关
participant 充电桩业务平台
participant 微信支付
database db

== 拔枪插枪 ==
充电桩 -> 充电桩:拔枪
充电桩 -> 充电桩网关:105-事件报送：拔枪（2）
    note right of 充电桩
    事件发送立即上传。为提高用户体验，枪状态除了在107报文枪状态上传外，
    也通过105事件上传。发生事件即刻上传。
    end note
充电桩网关 -->> 充电桩:106-回复
充电桩网关 ->> db:更新充电枪状态为7：已拔枪
充电桩 -> 充电桩:插枪
充电桩 -> 充电桩网关:105-事件报送：插枪（1）
充电桩网关 -->> 充电桩:106-回复
充电桩网关 ->> db:（记录插枪动作）

loop 周期报送，30s一次
充电桩 ->> 充电桩网关:107-充电枪状态
充电桩网关 -->> 充电桩:108-回复
充电桩网关 ->> db:更改充电枪状态

end
note right of 充电桩
充电枪状态：
0-空闲中
1-已插枪
2-启动中（收到启动命令，未进入充电前）
3-充电进行中
4-充电完成后未拔枪
5-预约状态
6-系统故障(不能给汽车充电,故障状态下即使插上充电枪仍然反馈故障状态)
end note

== 扫码 ==
h5 -> 充电桩业务平台:扫码
     note right of 充电桩
     参数：充电枪id
     end note
充电桩业务平台 -> db:查询充电枪状态，为1时可正常启动
alt 充电枪不可用
    充电桩业务平台 --> h5:充电枪未正确连接或其他不可用状态
else
    充电桩业务平台 --> h5:返回价格信息
    h5 -> 充电桩业务平台:确认充电

alt 充电枪不可用 余额不满足条件
    充电桩业务平台 -> 充电桩业务平台:检查用户余额
    充电桩业务平台 --> h5:余额不足，请预付款

== 进行预付 ==
    h5 --> 充电桩业务平台:发起预付
    充电桩业务平台 --> 充电桩业务平台:生成订单
    充电桩业务平台 --> 微信支付:发起预付，带上单号
    微信支付 --> 充电桩业务平台:待付状态
    充电桩业务平台 --> h5:待付状态
    h5 --> 微信支付:确认支付
    微信支付 --> h5:支付结果
    微信支付 --> 充电桩业务平台:通知支付结果
    充电桩业务平台 --> 充电桩业务平台:更改订单状态:已预付；预付金额

== 启动充电 ==
else 启动充电
     h5 -> 充电桩业务平台:去充电
     充电桩业务平台 -> 充电桩网关:设置soc
     充电桩业务平台 -> 充电桩网关:启动充电
     note right of 充电桩
     POST /charge/cgStartCmd
     参数：
     {
       "accountBalance": 22222,
       "cgNo": 2,
       "cpNo": "1101050009004110",
       "orderNo": "10088100881008811008810088100882",
       "stopCode": 456789
     }
     充电桩编号、充电枪编号、订单号、账户余额、屏幕停止充电码
     end note
     充电桩网关 -> 充电桩:112-启动充电；失败则最多重复三次
     充电桩 -> 充电桩:充电桩判断可以启动充电
     充电桩 --> 充电桩网关:111-启动充电回复

     充电桩 -> 充电桩:自检流程；

     loop 周期报送，30s一次
     充电桩 ->> 充电桩网关:107-充电枪状态。此时107报文工作状态为2
     充电桩网关 ->> db:更改充电枪状态
     充电桩网关 -->> 充电桩:108-回复
     end

     充电桩 ->> 充电桩网关:113-充电桩发送启动充电结果指令
        note right of 充电桩
        启动充电结果：1为失败；2为成功；
        失败原因：
        end note
     充电桩网关 -->> 充电桩:114回复
     note right of 充电桩网关
     根据启动充电结果更新：失败更新充电桩状态为6）；成功更新充电枪状态为3；
     失败原因：
     end note
     充电桩网关 -->> db:更新充电枪状态
     充电桩网关 -->> 充电桩业务平台:启动结果

     充电桩业务平台 -> h5:充电结果
     alt 充电桩启动充电失败
         h5 --> h5:充电桩启动充电失败，请重新插拔枪或换一台充电桩
     else 充电桩启动充电成功
         h5 --> h5:充电中页面


== 充电中 ==
         loop 周期报送，30s一次
         充电桩 ->> 充电桩网关:107-充电枪状态。此时107报文工作状态为3
         充电桩网关 ->> db:更改充电枪状态
         充电桩网关 -->> 充电桩:108-回复
         充电桩业务平台 -> h5:展示充电中信息，通过websocket实时更新数据
         end
         note right of 充电桩
         当剩余金额0.5元时停止充电。故障码为1005
         end note
== 停止充电 ==
         alt 充电桩停止充电
            充电桩 ->> 充电桩网关:117账单报文
            充电桩网关 ->> 充电桩:118
            充电桩网关 ->> db:记录账单信息
            充电桩网关 ->> 充电桩业务平台:停止充电
            充电桩业务平台 ->> h5:充电已停止
         else 平台停止充电
            h5 -> 充电桩业务平台:停止充电
            充电桩业务平台 -> 充电桩网关:停止充电
                 note right of 充电桩
                 POST /charge/cgStopCmd
                 参数：
                 {
                   "cgNo": 2,
                   "cpNo": "1101050009004110",
                   "orderNo": "10088100881008811008810088100882"
                 }
                 end note
            充电桩网关 ->> 充电桩:116
            充电桩 ->> 充电桩网关:115

            充电桩 ->> 充电桩网关:117账单报文
            充电桩网关 ->> db:记录账单信息
            充电桩网关 ->> 充电桩:118

            充电桩业务平台 ->> h5:停止结果

            alt 停止成功
                 h5 ->> 充电桩业务平台:查询账单
                 loop 循环查询，间隔1s、3s、6s。
                 充电桩业务平台 --> db:查询账单，根据账单表更新订单表
                 end
                  充电桩业务平台 ->> h5:账单
            end

         end

            alt 有预付款
                alt 预付款有剩余
                      充电桩业务平台 --> 微信支付:申请退款
                end
            end
        end
    end
end









@enduml