@startuml

actor h5

participant 用户系统
participant 订单系统
participant 人审系统
participant 风控系统
participant 支付系统

activate h5
h5 -> 用户系统: 手机号进行注册，或者第三方登陆进行注册
用户系统 -> 订单系统: 同步用户注册信息
h5 ->订单系统: 保存身份证、银行卡、活体认证、紧急联系人、社会信息
订单系统 ->风控系统: 身份证、银行卡、活体认证
订单系统 -->h5: 身份证、银行卡、活体认证是否通过验证？
alt 验证通过
    h5 -> h5:不允许修改
else 验证失败
    h5 ->订单系统: 允许重新进行上传验证
end
deactivate h5

h5 -> 订单系统: 下单，创建订单
订单系统 -> 订单系统: 校验认证信息状态否通过，是否有手机号码，是否有未完成订单
alt 通过
      订单系统 --> h5:订单待审核
      订单系统 -> 风控系统:机审风控决策
      风控系统 --> 订单系统:风控决策结果
      订单系统 -> 订单系统:更新订单状态：人审、拒绝、或通过

      alt 人审
            人审系统 -> 订单系统:审核，通过或拒绝
      end

      alt 通过
           人审系统 -> 支付系统:放款审核，如通过，则进行放款
      end

 else 不通过
      订单系统 --> h5:请重新提交认证未通过的身份信息，或补充手机号码等
 end


@enduml