@startuml

actor h5

participant 用户中心
database 用户库
database redis

== 获取验证码 ==
h5 -> 用户中心:请求获取验证码。\n地址：/public/sms/verifyCode
用户中心 -> 用户中心:生成六位随机数code，\n以及随机key(返回给前端，避免code被偷看，用到别的地方)
用户中心 -> 短信平台:code发送给手机
短信平台 -> 手机:发送短信
短信平台 --> 用户中心:发送成功
用户中心 -> h5:key发送给客户端
== 校验 ==
h5 -> 用户中心:登录。\n地址：/user/public/register/phone \n参数：手机号，验证码code，验证码key
用户中心 -> 用户中心:校验验证码是否正确、手机号是否未注册
alt 验证码失效
    用户中心 --> h5:验证码已失效
else 验证码错误
     用户中心 --> h5:验证码错误
else 未注册
    用户中心 -> h5:手机号未注册
else 此客户端是否已经登录
    用户中心 -> h5:无需重复登录
else 已在移动端登录，且此处登录客户端为移动端
    用户中心 -> h5:禁止在移动端多端登录
== 登录 ==
else 登录
    用户中心 -> redis:如果未移动端登录，在redis中标记为移动端登录
    用户中心 -> redis:生成token，存入redis
    用户中心 -> 用户库:保存登录记录
    用户中心 --> h5:在响应头中返回token
end




@enduml