@startmindmap

title 表结构设计
* 表结构设计
** 要素

*** 实体（表）
**** 定义
*****_ 一张表是由列与行构成的二维表。\n表示对于业务非常重要或值得获取的事务及与之相关的信息集合。\n每一行标识一个实例，由主键唯一标识；每个字段标识一个信息指标。
**** 根据独立性分类
***** 强实体
******_ 强实体可以独立存在，用来表示相对独立的人、事或地点。
***** 弱实体
******_ 弱实体至少依赖于一个其他的实体，这意味着如果不引用其他实体的实例，就无法检索弱实体的实例，例如订单。
**** 分类
***** 中心表
***** 子集表
******_ 其实例为某张表的子集，与父表为1对1关系。\n其主键可直接采用父表的主键。例如用户详情表为用户表的子集表。\n如果一个表中某些字段常常出现空值，可考虑放到子集表中。
***** 关系表
******_ 用以标识两张表的多对多关系的表
***** 日志表
******_ 一般不会有更新操作的表，例如登录日志表
***** 验证表
******_ 一般不会有新增或更新操作的表，例如地区查找表

*** 属性（字段）
**** 定义
*****_ 字段代表所属表的主题的一个特征。\n是一则相对独立的信息，其值用以识别、描述、评估实体实例。
**** 域
***** 定义
******_ 域是某一属性所有可能取值的集合。
***** 类型
****** 格式域
*******_ 将数据指定为数据库中的标准类型，如整型、字符型、日期
****** 列表域
*******_ 类似于一个下拉列表，它由一个可选的有限值的集合组成，是格式域的精简。如订单状态。
****** 范围域
*******_ 要求取值介于最小值和最大值之间

*** 关系
**** 定义
*****_ 数据模型中的规则即为关系，被表示成一条连接两个实体的线段，用来说明实体间的规则或导航路径
**** 分类
***** 数据规则
****** 定义
*******_ 指示数据间如何关联。例如每种产品可以出现在一个或多个订单上；订单不能脱离有效产品存在。
****** 类型
******* 1对1
******* 1对多
******* 多对多
***** 行为规则
****** 删除规则\n避免孤立记录出现
*******_ 否定：保留记录但设置状态为不活动
*******_ 限制：必须先删除子表中记录，才能删除父表中记录
*******_ 级联：删除父表中记录，将自动删除子表中相关记录
*******_ 作废：将子表中相关记录的外键值更改为null
*******_ 默认设置:将子表中相关记录更改为某默认值
****** 新增规则
*******_ 父表新增，通常需要同时新增子集表记录
****** 业务规则
*******_ 识别业务规则，例如订单包含5件以上产品时，优惠10%

*** 键
**** 定义
*****_ 键由一个或多个属性构成，其目的在于实施规则，有效数据检索，而且允许一个实体导航至另一个实体。
**** 候选键
*****_ 候选键是一个或多个可以唯一标识实体实例的属性。
***** 特点
****** 唯一性
*******_ 候选键可以建立唯一索引，不能标识多于一个实例。
****** 强制性
*******_ 不允许为空
****** 非异变性
*******_ 应该不会被更改
****** 最小化
*******_ 仅包含哪些用于唯一标识实体实例的属性。
***** 分类
****** 主键
******* 选取考虑
******** 简洁性
*********_ 通常选择属性数最少或最短的充当主键。\n更长的主键占据更多的索引空间。
******** 安全性
*********_ 包含敏感数据的属性不适合充当主键
****** 备用键
***** 分类
****** 单一键
****** 复合键
**** 分类
***** 自然键
***** 代理键
**** 其它
***** 外键
***** 辅助键

** 规范化
*** 定义
****_ 规范化是一个消除冗余的过程。\n以确保每个属性都是单值的，并且提供一个完全的、唯一的依赖于主键的事实。
*** 第一范式
****_ 确保属性单值。每个属性都是单值的，只能含有原子性（不可再分）的值。
*** 第二范式
****_ 确保完全性。每个实体都必须含有最小的属性集合来唯一标识每一个实体实例。\n主键外的其它字段必须依赖于完全的主键，而不能仅依赖于部分的主键。\n对于单字段主键，不会存在此问题
*** 第三范式
****_ 确保唯一性。每个属性都必须直接依赖于主键，而不依赖于实体内的其他属性。

** 反规范化
*** 定义
****_ 反规范化是选择性地违反规范化规则并在模型中重新引入冗余的过程。额外的冗余有助于降低数据检索时间。
*** 向上模式
****_ 主从表合并至主表。
*** 向下模式
****_ 主从表合并至从表。例如在关系表中存储其中一端的所有列，这样该端就消失了。

** 设计过程
*** 确认需求，建立概念模型
****_ 通过需求沟通，划分模块，识别相关的实体。定义重要的概念与术语，给出高层次的业务流程的解决方案。
*** 逻辑模型
****_ 基于业务规则的业务解决方案。识别业务规则，关键事务。
*** 物理模型
****_ 根据实际的技术选型，给出应用程序详细的技术解决方案及表结构设计


footer www.zrzhen.com
@endmindmap