@startuml

actor h5

participant 用户中心
participant 谷歌
database 用户库
database redis

h5 -> 谷歌: 用户在我方前端输入谷歌账户进行登陆
谷歌 --> h5: 临时令牌idToken
h5 -> 用户中心: 将idToken传到我方后端
用户中心 -> 谷歌: 用idToken获取用户谷歌账号信息

谷歌 --> 用户中心: 返回用户谷歌账号信息。判断该谷歌账号是否已绑定？
alt 已绑定
     用户中心 -> h5:进行登陆，返回用户token
else 未绑定
     用户中心 -> h5:返回账号为绑定的提示。
     用户中心 -> redis:同时将谷歌账号信息放入Redis缓存，key为idToken的哈希+IP（或移动设备唯一标识），value为谷歌账号信息。
     h5 -> h5:用户已有我方账号？
     alt 已有
          h5 -> 用户中心:用户登陆我方的账户，并标识为是需要绑定谷歌账号的登陆，并带上谷歌的ID token(改造原来的登陆接口);
          用户中心 -> redis:根据idToken从缓存中获取用户的谷歌账户信息;
          用户中心 -> 用户中心:进行谷歌账号绑定
          用户中心 -> h5:用户登陆成功，绑定谷歌账号成功。
     else 未有
          h5 -> 用户中心:用户跳过登陆，进入注册。\n以谷歌账户信息注册一个我方的新账户（缺乏手机号），\n并标识为是需要绑定谷歌账号，并带上谷歌的ID token（提供谷歌注册接口/google/register）;
          用户中心 -> redis:我方后端进行注册校验，注册成功则从缓存中获取用户的谷歌账户进行绑定，同时默认登陆
          用户中心 -> h5:注册成功
          h5 -> 用户中心:后续流程合适的场景中对必要的注册信息进行补充，
     end

end



@enduml