@startmindmap
* 商家会员管理

** 商家会员
*** 添加会员
****_ 地址：/v1/member/m/add
****_ 参数：
*****_ 必传：用户id ；
*****_ 非必传：会员昵称，会员邮箱，会员所属行业，会员证件类型，会员证件号码，会员地址，会员微信，会员QQ，会员头像，会员备注
*****_ 后端赋值：会员id
****_ 数据关联：同时新增会员钱包（事务一致）
****_ 返回：code为1表示添加成功，其他表示失败

**** 根据手机号查询用户列表（分页）
*****_ 地址：/v1/member/m/getUserListByPhone
*****_ 参数：必传：手机号
*****_ 数据关联：无
*****_ 返回：code为1表示添加成功，其他表示失败

*** 修改会员
****_ 地址：/v1/member/m/update
****_ 参数：必传：会员id ；非必传：会员昵称，会员邮箱，会员所属行业，会员证件类型，会员证件号码，会员地址，会员微信，会员QQ，会员头像，会员备注
****_ 数据关联：无
****_ 返回：code为1表示添加成功，其他表示失败

*** 删除会员
****_ 地址：/v1/member/m/del
****_ 参数：必传：会员id
****_ 数据关联：先删除会员钱包；删除会员钱包的前提是会员钱包余额为0
****_ 返回：code为1表示添加成功，其他表示失败

*** 分页查询会员列表
****_ 地址：/v1/member/m/findListByPage
****_ 参数：字段查询列表：排序字段；排序
****_ 数据关联：先删除会员钱包；删除会员钱包的前提是会员钱包余额为0
****_ 返回：code为1表示添加成功，其他表示失败

*** 根据会员id查询会员详情
****_ 地址：/v1/member/m/getById
****_ 参数：必传：会员id
****_ 数据关联：无
****_ 返回：{"code":1,"msg":"success","data":{"id":159385461110007,"merchantId":101950518928,"userId":88447809024,"memberNo":"zbrjLgiPnXSdA0H3NVkkhrZOmMiA1ehI","name":null,"email":"aaa@163.com","industryType":"ss","certificateType":1,"certificateNo":"sddddd","address":"Altai Krai/Yegoryevsky District","wechat":null,"qq":"","image":null,"remark":"","version":0,"creator":88447809024,"updator":88447809024,"createTime":"2020-07-04T09:23:31.000+0000","updateTime":"2020-07-04T09:23:31.000+0000"}}



** 团体会员
*** 新增团体会员
****_ 地址：/v1/team/m/add
****_ 参数：
*****_ 必传：name ；
*****_ 非必传：
*****_ 后端赋值：团体会员id
****_ 数据关联：同时新增团体会员钱包（事务一致）
****_ 返回：code为1表示添加成功，其他表示失败

*** 修改团体名称
****_ 地址：/v1/team/m/updateName
****_ 参数：团体id，name
****_ 数据关联：无
****_ 返回：code为1表示添加成功，其他表示失败

*** 删除团体会员（同步删除团体成员关联）
****_ 地址：/v1/team/m/del
****_ 参数：必传：团体会员id
****_ 数据关联：先删除团体钱包；删除团体钱包的前提是团体钱包余额为0
****_ 返回：code为1表示添加成功，其他表示失败

*** 查询团体会员列表
****_ 地址：/v1/team/m/findListByPage
****_ 参数：当前页位置，每页条数
****_ 数据关联：无
****_ 返回：code为1表示添加成功，其他表示失败

*** 根据团体id查询团体详情
****_ 地址：/v1/team/m/getById
****_ 参数：必传：团体id
****_ 数据关联：无
****_ 返回：

*** 根据团体id查询团体包含的成员列表（分页）(todo)
****_ 地址：/v1/team/m/findMemberListByPage
****_ 参数：团体id,当前页位置，每页条数
****_ 数据关联：无
****_ 返回：code为1表示添加成功，其他表示失败

*** 给团体新增成员
****_ 地址：/v1/team/m/addMember
****_ 参数：
*****_ 必传：团体id ；会员id
*****_ 非必传：
*****_ 后端赋值：无
****_ 数据关联：会员必须存在
****_ 返回：code为1表示添加成功，其他表示失败

**** 根据手机号搜索团体成员列表
*****_ 地址：/v1/team/m/findMemberListByPage
*****_ 参数：团体id，手机号
*****_ 数据关联：
*****_ 返回：code为1表示添加成功，其他表示失败

@endmindmap